### ISSUE TITLE
infon-devel: depends on python-gtksourceview2 which is deprecated

### ISSUE THREAD

**Issue by nomeata** [dividuum/infon#1]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822587:

> infon-devel depends on python-gtksourceview2, which is long
> deprecated and going to be removed from the archive. infon-devel
> should switch to using the GObject Introspection bindings for
> gtksourceview, gir1.2-gtksource-3.0.
> 
> This would mean switching to GObject Introspection for other bindings
> as well, e.g. GLib and GTK+ 3.

My conclusion is to remove infon-devel from Debian. @dividuum, do you agree?

**Comment by dividuum** [comment]
Ok. It's a bit sad, but as there is no one maintaining it: Go ahead.
